name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2.4.2
    - name: Setup SDK
      uses: actions/setup-dotnet@v2.1.0
    - name: Build with dotnet
      run: dotnet build -c Release
